spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://xxx/sell?characterEncoding=utf-8&useSSL=false
      username: xxx
      password: xxx

